### get hello
GET http://localhost:3000

### Create a new user
POST http://localhost:3000/users/signup
content-type: application/json

{
    "email" : "keval@gmail.com",
    "password" : "123"
}

### sign in  user
POST http://localhost:3000/users/signin
content-type : application/json

{
    "email" : "keval@gmail.com",
    "password" : "123"
}

### signout user
POST HTTP://localhost:3000/users/signout

### get user by id
GET http://localhost:3000/users/3

### get users by email
GET http://localhost:3000/users?email=dev@gmail.com

### delete user by id
DELETE  http://localhost:3000/users/4

### update user by id
PATCH  http://localhost:3000/users/3
content-type : application/json

{
    "password": "123"
}

###set color
GET http://localhost:3000/users/colors/red

###get color
GET http://localhost:3000/users/colors

### get self
GET http://localhost:3000/users/whoami